# Generated by Django 4.1.5 on 2023-02-20 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Accounts', '0002_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_category', models.CharField(max_length=50)),
                ('project_name', models.CharField(max_length=50)),
                ('project_description', models.TextField(max_length=1000)),
                ('project_picture', models.ImageField(blank=True, null=True, upload_to='project_pictures/')),
                ('project_link', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Certification_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Cofee_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Skill_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='background_picture',
            field=models.ImageField(blank=True, null=True, upload_to='background_pictures'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='logo_picture',
            field=models.ImageField(blank=True, null=True, upload_to='logo_pictures'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures'),
        ),
        migrations.DeleteModel(
            name='Education',
        ),
    ]
