# Generated by Django 4.1.5 on 2023-02-20 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Accounts', '0004_alter_userprofile_resume_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_edu', models.CharField(blank=True, max_length=10, null=True)),
                ('pg_field', models.CharField(blank=True, max_length=50, null=True)),
                ('pg_univ', models.CharField(blank=True, max_length=50, null=True)),
                ('pg_city', models.CharField(blank=True, max_length=50, null=True)),
                ('pg_year', models.IntegerField(blank=True, null=True)),
                ('pg_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ug_field', models.CharField(blank=True, max_length=50, null=True)),
                ('ug_univ', models.CharField(blank=True, max_length=50, null=True)),
                ('ug_city', models.CharField(blank=True, max_length=50, null=True)),
                ('ug_year', models.IntegerField(blank=True, null=True)),
                ('ug_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tlv_field', models.CharField(blank=True, max_length=50, null=True)),
                ('tlv_univ', models.CharField(blank=True, max_length=50, null=True)),
                ('tlv_city', models.CharField(blank=True, max_length=50, null=True)),
                ('tlv_year', models.IntegerField(blank=True, null=True)),
                ('tlv_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ten_univ', models.CharField(blank=True, max_length=50, null=True)),
                ('ten_city', models.CharField(blank=True, max_length=50, null=True)),
                ('ten_year', models.IntegerField(blank=True, null=True)),
                ('ten_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
