# Generated by Django 4.1.5 on 2023-03-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_alter_project_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_name',
            field=models.CharField(max_length=1000),
        ),
    ]
