# Generated by Django 4.1.5 on 2023-01-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Collegname', models.CharField(default='NHCE', max_length=100)),
                ('Cgpa', models.IntegerField(default=0)),
            ],
        ),
    ]
